### ISSUE TITLE
parameters

### ISSUE THREAD

**Issue by shubaivan** [lucascherifi/GoogleDriveBundle#1]
google drive api give parameters:

```
"client_id"
"project_id"
"auth_uri"
"token_uri"
"auth_provider_x509_cert_url"
"client_secret"
```

in install lost point about parametrers from service

gdrive_directory_base_id
gdrive_directory_splited_id
kasifi_gdrive.google_drive_client_email
kasifi_gdrive.google_auth_sub
gdrive_oauth_https_callback_prefix

by name not undersatnd what parameters your mean ? 
and you declareted: 

Resources Finder:
- Search a resource
- List children of a resource
- Get resource metadata
- Download files

where realization for download file example ?

**Comment by mobula9** [comment]
You're right. I'll add it to the documentation. Thanks !

**Comment by mobula9** [comment]
@shubaivan: You can update the bundle to the 0.8.3 via `composer update lucascherifi/google-drive-bundle`.

Regards,

Lucas.
